### ISSUE TITLE
Permitir passar mensagem customizada no no job `update-pr`

### ISSUE THREAD

**Issue by cebindani** [cebindani/reusable-workflows#3]
Atualmente o código atual está com uma mensagem fixa, da seguinte forma:

```yaml
  update-pr:
    name: Update PR body
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Body
        uses: chiaretto/github-action-concat-pr-body@master
        with:
          github-token: "${{ secrets.repo-token }}"
          message: "This pull request generated the following artifacts."
          replace-last-message: false
```

Permitir passar via `workflow_call.inputs` o parâmetro `message`
